export const ItemData = [
  {
    ItemCode: '100038513',
    ItemName: 'Canon EOS 80D (Body) +SDHC16GBC10+กระเป๋ากล้อง+ฟิล์มกันรอย',
    fullPrice: '39900',
    SellPrice: '24590',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'กล้องดิจิตอล ',
    groupDesc: 'กล้อง DSLR',
  },
  {
    ItemCode: '100067674',
    ItemName: 'PS4 Pro CUH-7106B 1TB Black ประกันศูนย์ไทย',
    fullPrice: '19500',
    SellPrice: '13890',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'เกมและเครื่องเล่น ',
    groupDesc: 'เครื่องเกม PlayStation',
  },
  {
    ItemCode: '1000878332',
    ItemName:
      'น้ำยาหม้อน้ำ ไอซิน Aisin ขนาด สีชมพู Super Long life Coollant / น้ำยาหล่อเย็น Aisin ขนาด4ลิตร',
    fullPrice: '350',
    SellPrice: '319',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'น้ำมันเครื่องและของเหลว',
  },
  {
    ItemCode: '100094558',
    ItemName:
      'PS4 PRO : JET BLACK [1TB] ประกันศูนย์ SONY ไทย [เมนูภาษาไทย] [4K] [HDR] [7106]',
    fullPrice: '14590',
    SellPrice: '14390',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'เกมและเครื่องเล่น ',
    groupDesc: 'เครื่องเกม PlayStation',
  },
  {
    ItemCode: '1001020615',
    ItemName: 'OnePlus 8 128GB Ram8/256GB Ram12 ร้าน TreeMobile / Tree Mobile',
    fullPrice: '23900',
    SellPrice: '17899',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1001200268',
    ItemName:
      'Oppo Reno 2 (Ram8/256GB) เครื่องใหม่มือ1,ศูนย์ไทยมีประกัน (Snapdragon 730G) ส่งฟรี!',
    fullPrice: '17990',
    SellPrice: '11980',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '100161551',
    ItemName:
      'SHELL น้ำมันเครื่อง RIMULA R4X 15W-40 ดีเซล รถบรรทุกงานหนัก 6 ลิตร ฟรี 1 ลิตร',
    fullPrice: '860',
    SellPrice: '745',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '100161552',
    ItemName:
      'SHELL น้ำมันเครื่อง RIMULA R4X 15W-40 ดีเซล รถบรรทุกงานหนัก 6 ลิตร (ฟรี 1 ลิตร มูลค่า 465 บาท) (2 แกลลอน)',
    fullPrice: '1670',
    SellPrice: '1449',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '100357452',
    ItemName:
      'VStarcam C18S 1080P Outdoor IP Camera กล้องวงจรปิดไร้สาย ภายนอก 2.0ล้านพิกเซล',
    fullPrice: '2590',
    SellPrice: '1450',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'กล้องรักษาความปลอดภัย.. ',
    groupDesc: 'กล้องรักษาความปลอดภัย',
  },
  {
    ItemCode: '100407826',
    ItemName:
      'Elit ชุดปะยางรถยนต์ ชุดปะยางฉุกเฉิน ขนาดพกพา Tire Repair Tool Set รุ่น TRT874-YU',
    fullPrice: '405',
    SellPrice: '121',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'ล้อและยางรถยนต์',
  },
  {
    ItemCode: '100502532',
    ItemName:
      'Bridgestone 195/65-15 ER300 4 เส้น ปี 19 (ฟรี จุ๊บยาง 4 ตัว มูลค่า 200 บาท)',
    fullPrice: '11600',
    SellPrice: '7128',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'ล้อและยางรถยนต์',
  },
  {
    ItemCode: '100586331',
    ItemName: 'Eachine E010 โดรนสำหรับ โมเป็น FPV racing(สีแดง)',
    fullPrice: '2896',
    SellPrice: '699',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'แก็ดเจ็ต ',
    groupDesc: 'โดรน',
  },
  {
    ItemCode: '1007366277',
    ItemName: 'โทรศัพท์มือถือ Wiko Y61',
    fullPrice: '2199',
    SellPrice: '2199',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '100925322',
    ItemName:
      'Beauty Jewelry เครื่องประดับผู้หญิง แหวนเพชรคลาสสิค ยอดนิยม เงินแท้ 92.5 sterling silver ประดับเพชรสวิส CZ รุ่น RS2071-RR เคลือบทองคำขาว',
    fullPrice: '790',
    SellPrice: '299',
    departmentDesc: 'เครื่องแต่งตัว',
    categoryDesc: 'เครื่องประดับผู้หญิง ',
    groupDesc: 'เครื่องประดับแฟชั่น',
  },
  {
    ItemCode: '101186887',
    ItemName:
      'Marino รองเท้า รองเท้าผ้าใบแฟชั่น รองเท้าผ้าใบผู้หญิงสีดำ รองเท้าผ้าใบผู้ชาย No. A011 - Black',
    fullPrice: '299',
    SellPrice: '83',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'เสื้อผ้า ',
    groupDesc: 'เสื้อและเสื้อยืด',
  },
  {
    ItemCode: '101187945',
    ItemName:
      'Marino รองเท้า รองเท้าผ้าใบแฟชั่น รองเท้าผ้าใบผู้หญิงสีดำ รุ่น A011 - Black',
    fullPrice: '399',
    SellPrice: '87',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'เสื้อผ้า ',
    groupDesc: 'เสื้อและเสื้อยืด',
  },
  {
    ItemCode: '101207506',
    ItemName: 'กางเกงขาสั้นฮานาโกะ',
    fullPrice: '250',
    SellPrice: '89',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'เสื้อผ้า ',
    groupDesc: 'กางเกงขาสั้น',
  },
  {
    ItemCode: '1014398410',
    ItemName: 'Redmi Note 9 EU 3+64GB',
    fullPrice: '4799',
    SellPrice: '4799',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1017616030',
    ItemName:
      'Huawei nova 7i Free ฟิล์มกระจก+Huawei mini tripod มูลค่า 990 บาท',
    fullPrice: '8990',
    SellPrice: '8290',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1018670541',
    ItemName:
      '8.1% ใหม่ 9.1% ใหม่ 9.9% สมาร์ทโฟนใหม่ 5c / 4 / 4s WiFi เวอร์ชัน 8G 16G',
    fullPrice: '1560',
    SellPrice: '881',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1020048452',
    ItemName:
      'Apple_iphone5s ไอโฟน5s โทรศัพท์ไอโฟน 5s มือ2 ใหม่95%-99%ครับ 16/32GB อุปกรณ์ครบถ้วน พร้อมชุดชาร์จ สภาพใหม่ 90%-95% โทรศัพท์มือถือใหม รับประกันไม่มีล็อคไม่มี ID, ไม่ต้องถอดชิ้นส่วนอุปกรณ์ครบถ้วน พร้อมชุดชาร์จ',
    fullPrice: '3900',
    SellPrice: '1799',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1023232244',
    ItemName:
      'OVANA V12 P30 PRO ความจำ RAM 3GB / ROM 32GB หน้าจอกว้าง 6.35 นิ้ว รับประกันศูนย์ไทย 1 ปี แบตเตอรี่ 3500 mAh ระบบสามารถตั้งค่าด้วย สแกนใบหน้าได้',
    fullPrice: '5990',
    SellPrice: '1450',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1023310936',
    ItemName:
      '[Official]INFINIX HOT 9 PLAY (2+32GB) จอใหญ่ 6.82" แบตใหญ่ 6,000 mAh',
    fullPrice: '2890',
    SellPrice: '2890',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '102398600',
    ItemName:
      '2017 มาใหม่ล่าสุดฤดูหนาวผู้หญิงรองเท้าบูตลุยหิมะสำหรับผู้หญิงแฟชั่นหลอดขนาดกลางกับ WARM รองเท้าบูทพลัสเวลเวทกันน้ำ Anti - SLIP กับ Tassels 35 (สีดำ) - INTL',
    fullPrice: '2044',
    SellPrice: '511',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'รองเท้า ',
    groupDesc: 'รองเท้าบูท',
  },
  {
    ItemCode: '1025730187',
    ItemName:
      'P40 Pro 6.35นิ้ว 6GB+128GBแบตเตอรี่: 4200mAh/สเปคแท้/เครื่องแท้ ประกันศูนย์1ปี/ โทรศัพท์ มือถือ รุ่นใหม่ล่าสุด ราคาถูก #ราคาถูกที่สุด ชุดพิเศษ แถมฟรี ฟิล์มกันรอย+เคส+AIMI',
    fullPrice: '8699',
    SellPrice: '1849',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '103085962',
    ItemName:
      'แอมป์ฤดูร้อนของผู้หญิงชุดคอดอกไม้ฝ้ายชุดผ้าลินินชายหาดแขนกุดชุดเดรสยาวหรูหรา - นานาชาติ',
    fullPrice: '630',
    SellPrice: '252',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'เสื้อผ้า ',
    groupDesc: 'ชุดเดรส',
  },
  {
    ItemCode: '1035662279',
    ItemName:
      'SHELL น้ำมันเครื่อง HELIX HX8 5W-30 ดีเซล คอมมอนเรล เกรดสังเคราะห์ สังเคราะห์แท้100% ( 6 ลิตร ฟรี 1 ลิตร )',
    fullPrice: '1800',
    SellPrice: '1296',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '103635627',
    ItemName: 'GAMING CASE - Intel® Core™ Processor i5-6400 GTX-1050 RAM 8GB',
    fullPrice: '19999',
    SellPrice: '16999',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'คอมพิวเตอร์ตั้งโต๊ะ ',
    groupDesc: 'เกมมิ่ง',
  },
  {
    ItemCode: '103638853',
    ItemName:
      'ที่จับมือถือ 3 in 1 เอนกประสงค์ ในรถยนต์ Car Phone Holder ยืดและหมุนได้ 360 องศา',
    fullPrice: '199',
    SellPrice: '45',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'อุปกรณ์เสริมภายในรถยนต์',
  },
  {
    ItemCode: '1038732692',
    ItemName:
      'Huawei Y5P (2/32GB) + รับฟรี หูฟัง JBL C150SI in-Ear Earphone (สินค้าจะเริ่มจัดส่งวันที่ 5 มิ.ย. เป็นต้นไป)',
    fullPrice: '2999',
    SellPrice: '2999',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1042898794',
    ItemName: 'Huawei Y5P (2/32GB) (โทรศัพท์มือถือ)',
    fullPrice: '2599',
    SellPrice: '2599',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '104353058',
    ItemName:
      'เสื้อคลุมเกาหลี ผ้าชีฟอง แฟชั่นเกาหลี ผ้าโปร่งบางเบา [มีตารางไซส์ในรายละเอียดสินค้าแล้ว] [มี 2 ไซส์ M / L] สวมใส่สบาย พริ้วๆ ชิลๆ [โปรดคลิกตัวเลือกแบบสินค้าที่ต้องการ มีเบอร์ 01-26] แถมฟรี!! กระเป๋าแฟชั่น 99 บาท เสื้อคลุม1',
    fullPrice: '500',
    SellPrice: '139',
    departmentDesc: 'แฟชั่นผู้หญิง',
    categoryDesc: 'เสื้อผ้า ',
    groupDesc: 'ชุดเดรส',
  },
  {
    ItemCode: '1043830238',
    ItemName:
      'โทรศัพท์มือถือ NOVA PHONE รุ่น Play5 รุ่นใหม่ จอใหญ่ 6.6นิ้ว 2020 ราคาถูก ถ่ายรูปสวย รองรับซิม 4G / 3G สเปคแท้/เครื่องแท้ ประกันศูนย์1ปี',
    fullPrice: '1900',
    SellPrice: '1321',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1044686699',
    ItemName:
      'โทรศัพท์มือสอง Smartphone Phone X 64GB ( 99% New ) รับประกัน 1 ปี',
    fullPrice: '12869',
    SellPrice: '12869',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '104652311',
    ItemName:
      'Phoenix B2C ผู้หญิงพังค์โกธิคพลอยเทียมปีก Skulls หู Cuff คลิปต่างหูสำหรับหูซ้าย - นานาชาติ',
    fullPrice: '290',
    SellPrice: '59',
    departmentDesc: 'เครื่องแต่งตัว',
    categoryDesc: 'เครื่องประดับผู้หญิง ',
    groupDesc: 'เครื่องประดับแฟชั่น',
  },
  {
    ItemCode: '1046726554',
    ItemName:
      '(ผ่อน0%)Vivo วีโว่ Mobile โทรศัพท์มือถือ สมาร์ทโฟน รุ่น Y50 แบตเตอรี่ 5000mAh หน้าจอ 6.53 นิ้ว Ram 8+128GB (รับประกันตัวเครื่อง 2 ปี)',
    fullPrice: '7999',
    SellPrice: '7999',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1048334947',
    ItemName: 'Shell RIMURA R3+ เชลล์ ริมูล่า R3+ ขนาด 6ลิตร แถม 1 ลิตร',
    fullPrice: '800',
    SellPrice: '649',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '10492308',
    ItemName:
      'PS4 SLIM : PARTY BUNDLE [500GB] ประกันศูนย์ SONY ไทย [HDR] [CUH-2106]',
    fullPrice: '12990',
    SellPrice: '12493',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'เกมและเครื่องเล่น ',
    groupDesc: 'เครื่องเกม PlayStation',
  },
  {
    ItemCode: '1049862331',
    ItemName:
      '[ผ่อน 0%] ใหม่ล่าสุด!! OPPO A12 4GB+ROM 64GB | รับประกันนาน 12 เดือน',
    fullPrice: '4999',
    SellPrice: '4999',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1049924870',
    ItemName: 'Samsung Galaxy A10s ***รับประกันศูนย์ 1 ปี***',
    fullPrice: '4090',
    SellPrice: '3270',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '10502138',
    ItemName: 'Karmakamet ถุงหอม กลิ่นวนิลลา Vanilla Javanese',
    fullPrice: '550',
    SellPrice: '400',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'อุปกรณ์เสริมภายในรถยนต์',
  },
  {
    ItemCode: '105118',
    ItemName:
      'PS4 SLIM : JET BLACK [500GB] ประกันศูนย์ SONY ไทย [HDR] [CUH-2106]',
    fullPrice: '10990',
    SellPrice: '10811',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'เกมและเครื่องเล่น ',
    groupDesc: 'เครื่องเกม PlayStation',
  },
  {
    ItemCode: '105274348',
    ItemName: '7-fourteen ชุดประยางฉุกเฉิน',
    fullPrice: '299',
    SellPrice: '77',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'ล้อและยางรถยนต์',
  },
  {
    ItemCode: '105313448',
    ItemName: 'Apple iPhone 7 Plus by Banana IT (โทรศัพท์มือถือ)',
    fullPrice: '16500',
    SellPrice: '15500',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1061518816',
    ItemName:
      '(พร้อมส่ง )Gal axy S20 มือถือจอหยดน้ำ 6.8 นิ้ว6GB+128GBจอ HD1080pแท้ 100%มีเอกสารรับรอง AIS DTAC TRUE ใช้แอพธนาคารไทยได้ ผ่านการรับรองจากกสทช',
    fullPrice: '11900',
    SellPrice: '3672',
    departmentDesc: 'อุปกรณ์ อิเลกทรอนิคส์',
    categoryDesc: 'โทรศัพท์มือถือ',
    groupDesc: 'โทรศัพท์มือถือ',
  },
  {
    ItemCode: '1063104265',
    ItemName:
      'น้ำมันเครื่อง เชลล์ ริมูล่า อาร์ 4 เอ็ก 15W40 Shell Rimula R4 X 15W-40 ขนาด 6 ลิตร สำหรับรถเครื่องยนต์ดีเซล',
    fullPrice: '775',
    SellPrice: '775',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '1063212817',
    ItemName: 'เชลล์ เฮลิกส์ ดีเซล HX5 Shell Helix HX5 15W-40 ขนาด 6 ลิตร',
    fullPrice: '700',
    SellPrice: '700',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '1064552867',
    ItemName: 'เชลล์ เฮลิกส์ HX7 Shell Helix HX7 5W-40 ขนาด 4 ลิตร',
    fullPrice: '845',
    SellPrice: '845',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '1064682191',
    ItemName: 'เชลล์ เฮลิกซ์ Shell Helix HX8 5W-40 ขนาด 4 ลิตร',
    fullPrice: '1115',
    SellPrice: '1115',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'น้ำมันเครื่องและของเหลว ',
    groupDesc: 'น้ำมันเครื่อง',
  },
  {
    ItemCode: '106524458',
    ItemName:
      'น้ำมันเครื่องเบนซินสังเคราะห์ 100% BCP (บางจาก) FURIO SAE 5W-30 ขนาด 4 ลิตร ฟรี หัวเชื้อเบนซิน 1 ขวด กรวยเติมน้ำมัน 1 อัน',
    fullPrice: '2659',
    SellPrice: '1189',
    departmentDesc: 'ยานยนต์ และ อุปกรณ์',
    categoryDesc: 'รถยนต์และอุปกรณ์ ',
    groupDesc: 'น้ำมันเครื่องและของเหลว',
  },
];
